### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Lauchturm** [ycps/vrep-env#1]
Hi Yuri,
your repo looks like I could use it very well for my bachelor thesis, but without a specified license I am not allowed to use or modify it. Thus you would help me a lot if you could add a license to the repo.

I found https://choosealicense.com/ to be very helpful in that decision.

If you prefer so, I could also create a pull request adding the license.

Best regards,
Julian

**Comment by ycps** [comment]
Hi Julian,
thanks for the feedback. I have added the MIT License to the repo.
Feel free to contact me regarding this project or send a pull request in the repo.
Cheers,
Yuri

**Comment by Lauchturm** [comment]
Thank you very much! 
If I find anything that needs to be changed or added, I will gladly send a PR
